name: "pizza-app"
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6

      - name: Login to docker hub
        uses: docker/login-action@v3.7.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build/Push docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pizza-app:latest /app
          docker push ${{ secrets.DOCKER_USERNAME }}/pizza-app:latest

  deploy-stage:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Copy docker-compose/nginx via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "/compose.yml,/nginx.conf"
          target: "/home/ec2-user/app"

      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/app
            docker compose pull
            docker compose up -d
            docker image prune -f
